# Generated by Django 5.0.1 on 2024-11-25 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_product_options_alter_reservation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workordernote',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='workordernote',
            name='is_cancel_reason',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workordernote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workordernote',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workordernote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workordernote',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.workorder'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('add', 'Entrada'), ('remove', 'Salida')], max_length=10, verbose_name='Tipo de Movimiento')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshop.product', verbose_name='Producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
